# -*- coding: utf-8 -*-
"""Wordcloud

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFaD-5P5Vc8GMKKVUz_YoOgbzSpUYUKs
"""

import matplotlib.pyplot as plt
import numpy as np
from wordcloud import WordCloud
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')

with open("/content/text.txt", "r", encoding="UTF-8") as file:
    text= file.read()

stop_words=set(stopwords.words("english"))

def data_preprocessing(data):
  data=data.lower()
  data_tokens=word_tokenize(data)
  preprocessed_text=[w for w in data_tokens if not w in stop_words]
  return " ".join(preprocessed_text)

data=data_preprocessing(text)
print(data)

word_cloud=WordCloud(
    background_color="black",
    colormap="viridis",
    contour_color="steelblue",
    contour_width=2
)

word_cloud.generate(data)
plt.figure(figsize=(12,12))
plt.imshow(word_cloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""**By using a Mask**"""

from PIL import Image
Mask=np.array(Image.open("/content/Twitter.png"))

word_cloud=WordCloud(
    mask=Mask,
    background_color="black",
    colormap="viridis",
    contour_color="steelblue",
    contour_width=2
)

word_cloud.generate(data)
plt.figure(figsize=(12,12))
plt.imshow(word_cloud, interpolation='bilinear')
plt.axis("off")
plt.show()